// define leds based on leg position and color

#define LEG0_COLOR_RED0 6
#define LEG0_COLOR_RED1 7
#define LEG0_COLOR_ORANGE 8
#define LEG0_COLOR_GREEN 5
#define LEG0_COLOR_BLUE 4
#define LEG0_COLOR_WHITE 10

#define LEG1_COLOR_RED0 0
#define LEG1_COLOR_RED1 1
#define LEG1_COLOR_ORANGE 2
#define LEG1_COLOR_GREEN 3
#define LEG1_COLOR_BLUE 14
#define LEG1_COLOR_WHITE 9

#define LEG2_COLOR_RED0 17
#define LEG2_COLOR_RED1 16
#define LEG2_COLOR_ORANGE 15
#define LEG2_COLOR_GREEN 13
#define LEG2_COLOR_BLUE 11
#define LEG2_COLOR_WHITE 12
